project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iambarat
      
format:
  html:
    theme: solar
    css: styles.css



